"""bundle_lib.py - the publish bundle contract ("pmp-bundle/1"), shared by the Modal app (makes + uploads bundles) and the
publisher on the EC2 box (verifies + merges them). Standard library only; Python >= 3.9.

A bundle is ONE deterministic tar.gz per model, uploaded to
    s3://bim-proprietary-data/cad-disk-extract/_state/pmp/bundles/<run>/<model_id>.tar.gz
holding exactly:

    bundle.json                    header (see HEADER_KEYS)
    scripts_manifest_rows.jsonl    one row per file under scripts/, sorted by path:
                                   {"path": "scripts/...", "bytes": n, "sha256": hex, "model_id": id, "source": str, "code_version": str}
    scripts/README.md              shared files: identical for every model of a package (the publisher refuses a
    scripts/requirements.txt       bundle whose shared file differs from the one already published in the package)
    scripts/steelbuild.py
    scripts/issues_lib.py
    scripts/<model_folder>/...     this model's folder (layout: MODEL_REQUIRED / MODEL_TOP_ALLOWED)

Paths in rows are relative to the PACKAGE folder ("scripts/..."), like the package's own manifest.jsonl relpaths.
scripts/scripts_manifest.jsonl is NOT in a bundle: the publisher regenerates it from the merged S3 tree.

API
    make_bundle(scripts_dir, out_path, header, sources)  -> dict(sha256, bytes, n_files, md5_b64)   (deterministic)
    verify_bundle(path, extract_to=None, expect=None)    -> Verified(header, rows, files, warnings, sha256, bytes)
                                                            raises BundleError(code, message) on the first hard problem
    upload_bundle(path, put_url, retries=4)              -> dict(status, etag, bytes, sha256)   (HTTP PUT; ETag == MD5 checked)
"""
from __future__ import annotations

import base64
import gzip
import hashlib
import io
import json
import os
import posixpath
import re
import stat
import tarfile
import time
import urllib.error
import urllib.parse
import urllib.request
import zlib

FORMAT = 'pmp-bundle/1'
HEADER_NAME = 'bundle.json'
ROWS_NAME = 'scripts_manifest_rows.jsonl'
SCRIPTS = 'scripts'
SHARED_FILES = ('README.md', 'requirements.txt', 'steelbuild.py', 'issues_lib.py')          # scripts/<name>, all required
MANIFEST_NAME = 'scripts_manifest.jsonl'                                                    # generated by the publisher only
STEP_SOURCES = ('ifc', 'db1', 'sds2')
HEADER_KEYS = ('format', 'run', 'model_id', 'pid', 'model_folder', 'step_relpath', 'step_source', 'code_version',
               'n_files', 'bytes', 'rows_sha256')
# model folder layout (relative to scripts/<model_folder>/)
MODEL_TOP_ALLOWED = ('build_model.py', 'build_issues_model.py', 'model_info.json', 'schedules', 'verification', 'issues', 'source',
                     # pmp-completion (publish_v2): the COMPLETED model
                     'build_completed_coloured.py', 'schedules_original', 'completed')
MODEL_REQUIRED = ('build_model.py', 'build_issues_model.py', 'model_info.json', 'schedules/parts.csv', 'schedules/issues.json',
                  'schedules/missing_parts.json', 'verification/verification.csv', 'issues/WHERE_TO_LOOK.md', 'source/provenance.json')
CONTENT_CHECKED = ('model_info.json', 'schedules/issues.json', 'schedules/missing_parts.json', 'source/provenance.json')
ISSUES_STEP_SUFFIX = '_ISSUES_highlighted.step'
MISSING_STEP_SUFFIX = '_MISSING_parts_only.step'
SOURCE_IFC_SUFFIXES = ('.ifc', '.ifczip', '.ifc.gz')          # db1 / sds2 models must ship their regenerated / emitted IFC
JUNK_NAMES = ('__pycache__', '.DS_Store', 'Thumbs.db')
JUNK_SUFFIXES = ('.pyc', '.pyo', '.tmp', '.part', '~')
# limits (gzip-bomb / runaway guards; >= 1 GB models are out of scope for v1)
MAX_FILES = 20000
MAX_FILE_BYTES = 1536 * 1024 ** 2
MAX_TOTAL_BYTES = 4 * 1024 ** 3
MAX_MEMBER_NAME = 700                     # bytes; the S3 key adds the target root + pid and must stay <= 1024
MAX_SOURCE_LEN = 512
MAX_CODE_VERSION_LEN = 128
RUN_RE = re.compile(r'^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$')
MODEL_ID_RE = re.compile(r'^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$')
_BAD_CHARS = re.compile(r'[\x00-\x1f\x7f\\]')
_ARCHIVE_ERRORS = (tarfile.TarError, OSError, EOFError, zlib.error)


class BundleError(Exception):
    """a hard problem: the bundle must not be published. .code is a short stable slug for logs."""

    def __init__(self, code, message):
        super().__init__(f'{code}: {message}')
        self.code = code
        self.message = message


class Verified:
    def __init__(self, header, rows, files, warnings, sha256, nbytes, root):
        self.header = header          # dict
        self.rows = rows              # list of row dicts, sorted by path
        self.files = files            # {path ("scripts/..."): local absolute path (None when not extracted)}
        self.warnings = warnings      # list of str
        self.sha256 = sha256          # of the .tar.gz
        self.bytes = nbytes           # of the .tar.gz
        self.root = root              # extraction dir or None


def sha256_file(path, bufsize=1 << 20):
    h = hashlib.sha256()
    with open(path, 'rb') as f:
        for b in iter(lambda: f.read(bufsize), b''):
            h.update(b)
    return h.hexdigest()


def _md5_b64(path):
    h = hashlib.md5()
    with open(path, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''):
            h.update(b)
    return base64.b64encode(h.digest()).decode()


def row_line(row):
    """the canonical serialisation of one manifest row (fixed key order)"""
    keys = ('path', 'bytes', 'sha256', 'model_id', 'source', 'code_version')
    extra = sorted(k for k in row if k not in keys)
    return json.dumps({k: row.get(k) for k in keys + tuple(extra)}, ensure_ascii=False) + '\n'


def check_component(c, what):
    """one path component: no separators / control chars / '.' '..' / surrounding whitespace / hidden or junk names"""
    if not c or c in ('.', '..'):
        raise BundleError('bad_path', f'{what}: empty, "." or ".." component')
    if _BAD_CHARS.search(c) or '/' in c:
        raise BundleError('bad_path', f'{what}: control character, backslash or slash in {c!r}')
    if c != c.strip():
        raise BundleError('bad_path', f'{what}: leading/trailing whitespace in {c!r}')
    if c.startswith('.') or c in JUNK_NAMES or c.endswith(JUNK_SUFFIXES):
        raise BundleError('junk_file', f'{what}: hidden / cache / temp name {c!r}')


def check_relpath(p, what='path'):
    if not isinstance(p, str) or not p:
        raise BundleError('bad_path', f'{what}: empty')
    if p.startswith('/') or posixpath.normpath(p) != p:
        raise BundleError('bad_path', f'{what}: not a normalised relative path: {p!r}')
    if len(p.encode('utf-8')) > MAX_MEMBER_NAME:
        raise BundleError('bad_path', f'{what}: longer than {MAX_MEMBER_NAME} bytes: {p[:80]!r}...')
    for c in p.split('/'):
        check_component(c, what)


def check_header(h):
    if not isinstance(h, dict):
        raise BundleError('bad_header', 'bundle.json is not an object')
    miss = [k for k in HEADER_KEYS if k not in h]
    if miss:
        raise BundleError('bad_header', f'bundle.json lacks {miss}')
    if h['format'] != FORMAT:
        raise BundleError('bad_header', f'format {h["format"]!r} != {FORMAT!r}')
    if not isinstance(h['run'], str) or not RUN_RE.match(h['run']):
        raise BundleError('bad_header', f'run {h["run"]!r} must match {RUN_RE.pattern}')
    if not isinstance(h['model_id'], str) or not MODEL_ID_RE.match(h['model_id']):
        raise BundleError('bad_header', f'model_id {h["model_id"]!r} must match {MODEL_ID_RE.pattern}')
    pid = h['pid']
    if not isinstance(pid, str) or not pid or '/' in pid or _BAD_CHARS.search(pid) or pid != pid.strip() or pid in ('.', '..'):
        raise BundleError('bad_header', f'pid {pid!r} is not a package folder name')
    check_component(h['model_folder'], 'model_folder')
    if h['model_folder'] in SHARED_FILES + (MANIFEST_NAME,):
        raise BundleError('bad_header', f'model_folder {h["model_folder"]!r} collides with a shared scripts/ file')
    sp = h['step_relpath']
    if not isinstance(sp, str) or not sp.startswith('model/step/'):
        raise BundleError('bad_header', f'step_relpath {sp!r} must start with model/step/')
    if h['step_source'] not in STEP_SOURCES:
        raise BundleError('bad_header', f'step_source {h["step_source"]!r} not in {STEP_SOURCES}')
    if not isinstance(h['code_version'], str) or not h['code_version'] or len(h['code_version']) > MAX_CODE_VERSION_LEN:
        raise BundleError('bad_header', 'code_version must be a non-empty string')


def _missing_count(data):
    """number of parts listed in schedules/missing_parts.json (bytes), or None when the shape is not recognised"""
    try:
        d = json.loads(data.decode('utf-8'))
    except Exception as e:  # noqa: BLE001 - reported as a hard error by the caller
        raise BundleError('bad_json', f'schedules/missing_parts.json does not parse: {type(e).__name__}: {e}')
    if isinstance(d, list):
        return len(d)
    if isinstance(d, dict):
        for k in ('parts', 'missing_parts', 'missing', 'items'):
            if isinstance(d.get(k), list):
                return len(d[k])
        for k in ('count', 'n', 'n_missing'):
            if isinstance(d.get(k), int):
                return d[k]
    return None


def check_layout(header, paths, contents=None, sizes=None, lenient=False):
    """paths: every 'scripts/...' file path of the bundle. contents: {path: bytes} of the CONTENT_CHECKED files;
    sizes: {path: bytes}. Returns warnings; raises BundleError on a hard layout problem (lenient turns layout problems
    other than safety ones into warnings)."""
    warns = []

    def bad(code, msg):
        if lenient:
            warns.append(f'{code}: {msg}')
        else:
            raise BundleError(code, msg)

    mf = header['model_folder']
    pre = f'{SCRIPTS}/{mf}/'
    model = sorted(p[len(pre):] for p in paths if p.startswith(pre))
    for p in paths:
        if not p.startswith(SCRIPTS + '/'):
            raise BundleError('bad_layout', f'{p!r} is outside scripts/')
        rest = p[len(SCRIPTS) + 1:]
        if '/' not in rest:
            if rest == MANIFEST_NAME:
                raise BundleError('bad_layout', f'scripts/{MANIFEST_NAME} must not be in a bundle (the publisher generates it)')
            if rest not in SHARED_FILES:
                raise BundleError('bad_layout', f'unexpected shared file scripts/{rest!r} (allowed: {SHARED_FILES})')
        elif not p.startswith(pre):
            raise BundleError('bad_layout', f'{p!r} is not in this model\'s folder scripts/{mf}/ (one model per bundle)')
    for s in SHARED_FILES:
        if f'{SCRIPTS}/{s}' not in paths:
            raise BundleError('missing_file', f'shared file scripts/{s} is missing')
    if not model:
        raise BundleError('missing_file', f'model folder scripts/{mf}/ is empty')
    tops = sorted({m.split('/')[0] for m in model})
    extra = [t for t in tops if t not in MODEL_TOP_ALLOWED]
    if extra:
        bad('bad_layout', f'unexpected entries in scripts/{mf}/: {extra} (allowed: {MODEL_TOP_ALLOWED})')
    for t in ('build_model.py', 'build_issues_model.py', 'model_info.json'):
        if any(m.startswith(t + '/') for m in model):
            raise BundleError('bad_layout', f'scripts/{mf}/{t} must be a file, not a folder')
    for r in MODEL_REQUIRED:
        if r not in model:
            bad('missing_file', f'scripts/{mf}/{r} is missing')
    iss = [m for m in model if m.startswith('issues/') and m.endswith(ISSUES_STEP_SUFFIX) and m.count('/') == 1]
    if len(iss) != 1:
        bad('missing_file' if not iss else 'bad_layout', f'scripts/{mf}/issues/ must hold exactly one *{ISSUES_STEP_SUFFIX} (found {len(iss)})')
    mis = [m for m in model if m.startswith('issues/') and m.endswith(MISSING_STEP_SUFFIX) and m.count('/') == 1]
    if len(mis) > 1:
        bad('bad_layout', f'scripts/{mf}/issues/ holds {len(mis)} *{MISSING_STEP_SUFFIX} files')
    if header['step_source'] in ('db1', 'sds2'):
        if not any(m.startswith('source/') and m.lower().endswith(SOURCE_IFC_SUFFIXES) for m in model):
            bad('missing_file', f'{header["step_source"]} model: scripts/{mf}/source/ must ship the regenerated/emitted IFC')
    if contents is not None:
        mp = contents.get(f'{pre}schedules/missing_parts.json')
        if mp is not None:
            n = _missing_count(mp)
            if n is None:
                warns.append('schedules/missing_parts.json: unrecognised shape, the MISSING-step check was skipped')
            elif n > 0 and not mis:
                bad('missing_file', f'missing_parts.json lists {n} parts but issues/*{MISSING_STEP_SUFFIX} is absent')
            elif n == 0 and mis:
                warns.append(f'missing_parts.json lists 0 parts but {mis[0]} is present')
        for name in CONTENT_CHECKED:
            data = contents.get(pre + name)
            if data is not None and name.endswith('.json'):
                try:
                    json.loads(data.decode('utf-8'))
                except Exception as e:  # noqa: BLE001
                    raise BundleError('bad_json', f'scripts/{mf}/{name} does not parse: {type(e).__name__}')
    for p, nb in sorted((sizes or {}).items()):
        if nb == 0:
            warns.append(f'empty file {p}')
    lower = {}
    for p in paths:
        lower.setdefault(p.lower(), []).append(p)
    clash = [v for v in lower.values() if len(v) > 1]
    if clash:
        raise BundleError('case_clash', f'paths differing only in case (break on macOS/Windows): {clash[:3]}')
    return warns


def check_rows(header, rows, actual):
    """rows: parsed scripts_manifest_rows.jsonl. actual: {path: (bytes, sha256)} of the extracted scripts/ files."""
    seen = set()
    for i, r in enumerate(rows):
        if not isinstance(r, dict):
            raise BundleError('bad_rows', f'row {i} is not an object')
        p = r.get('path')
        if p in seen:
            raise BundleError('bad_rows', f'duplicate row for {p!r}')
        seen.add(p)
        if p not in actual:
            raise BundleError('bad_rows', f'row for {p!r} but no such file in the bundle')
        nb, h = actual[p]
        if r.get('bytes') != nb:
            raise BundleError('sha_mismatch', f'{p}: row says {r.get("bytes")} bytes, file has {nb}')
        if r.get('sha256') != h:
            raise BundleError('sha_mismatch', f'{p}: row sha256 does not match the file content')
        if r.get('model_id') != header['model_id']:
            raise BundleError('bad_rows', f'{p}: row model_id {r.get("model_id")!r} != bundle model_id')
        s = r.get('source')
        if not isinstance(s, str) or not s.strip() or len(s) > MAX_SOURCE_LEN:
            raise BundleError('bad_rows', f'{p}: source must be a non-empty string <= {MAX_SOURCE_LEN} chars')
        cv = r.get('code_version')
        if not isinstance(cv, str) or not cv.strip() or len(cv) > MAX_CODE_VERSION_LEN:
            raise BundleError('bad_rows', f'{p}: code_version must be a non-empty string <= {MAX_CODE_VERSION_LEN} chars')
    unlisted = sorted(set(actual) - seen)
    if unlisted:
        raise BundleError('bad_rows', f'{len(unlisted)} files have no row, e.g. {unlisted[:3]}')
    if [r['path'] for r in rows] != sorted(r['path'] for r in rows):
        raise BundleError('bad_rows', 'rows are not sorted by path')


def make_bundle(scripts_dir, out_path, header, sources, code_versions=None):
    """build a deterministic bundle from an assembled scripts/ tree.

    scripts_dir: local folder that IS the scripts/ tree (holds the 4 shared files + <model_folder>/ only).
    header: dict with run, model_id, pid, model_folder, step_relpath, step_source, code_version (format/n_files/bytes/
            rows_sha256 are filled in here).
    sources: {path relative to scripts_dir: provenance string} or a callable(relpath) -> str; every file needs one.
    code_versions: optional {relpath: version} / callable; default = header['code_version'].
    The bundle is verified (verify_bundle) before this returns; raises BundleError when it would be refused."""
    files = []
    for dp, dn, fn in os.walk(scripts_dir):
        dn.sort()
        for f in sorted(fn):
            full = os.path.join(dp, f)
            rel = os.path.relpath(full, scripts_dir).replace(os.sep, '/')
            st = os.lstat(full)
            if not stat.S_ISREG(st.st_mode):
                raise BundleError('bad_member', f'{rel}: not a regular file (symlinks are not allowed)')
            files.append((f'{SCRIPTS}/{rel}', full, st.st_size))
    files.sort(key=lambda x: x[0])
    h = dict(header)
    h['format'] = FORMAT

    def pick(m, rel, default=None):
        if m is None:
            return default
        return m(rel) if callable(m) else m.get(rel, default)

    rows = []
    for p, full, nb in files:
        rel = p[len(SCRIPTS) + 1:]
        rows.append(dict(path=p, bytes=nb, sha256=sha256_file(full), model_id=h['model_id'], source=pick(sources, rel),
                         code_version=pick(code_versions, rel, h.get('code_version'))))
    rows_bytes = ''.join(row_line(r) for r in rows).encode('utf-8')
    h['n_files'] = len(rows)
    h['bytes'] = sum(r['bytes'] for r in rows)
    h['rows_sha256'] = hashlib.sha256(rows_bytes).hexdigest()
    h = {k: h[k] for k in HEADER_KEYS + tuple(sorted(k for k in h if k not in HEADER_KEYS))}
    check_header(h)
    head_bytes = (json.dumps(h, ensure_ascii=False, indent=1) + '\n').encode('utf-8')
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    tmp = out_path + '.tmp'

    def info(name, size):
        ti = tarfile.TarInfo(name)
        ti.size = size
        ti.mtime = 0
        ti.mode = 0o644
        ti.uid = ti.gid = 0
        ti.uname = ti.gname = ''
        ti.type = tarfile.REGTYPE
        return ti

    with open(tmp, 'wb') as raw:
        with gzip.GzipFile(filename='', mode='wb', fileobj=raw, mtime=0, compresslevel=6) as gz:
            with tarfile.open(fileobj=gz, mode='w', format=tarfile.PAX_FORMAT) as tf:
                tf.addfile(info(HEADER_NAME, len(head_bytes)), io.BytesIO(head_bytes))
                tf.addfile(info(ROWS_NAME, len(rows_bytes)), io.BytesIO(rows_bytes))
                for p, full, nb in files:
                    with open(full, 'rb') as f:
                        tf.addfile(info(p, nb), f)
    os.replace(tmp, out_path)
    v = verify_bundle(out_path)
    return dict(sha256=v.sha256, bytes=v.bytes, n_files=len(v.rows), md5_b64=_md5_b64(out_path), header=v.header,
                warnings=v.warnings)


def verify_bundle(path, extract_to=None, expect=None, lenient=False):
    """check a bundle completely. extract_to: folder to extract the scripts/ files into (must be empty or absent);
    without it the files are hashed while streaming and nothing is written. expect: optional dict(run=, model_id=,
    sha256=) the bundle must match (e.g. from its S3 key and the Modal index). Returns Verified; raises BundleError."""
    expect = expect or {}
    nb = os.path.getsize(path)
    bsha = sha256_file(path)
    if expect.get('sha256') and expect['sha256'] != bsha:
        raise BundleError('sha_mismatch', 'bundle sha256 differs from the expected one (Modal index)')
    if extract_to:
        os.makedirs(extract_to, exist_ok=True)
        if os.listdir(extract_to):
            raise BundleError('internal', f'extract dir {extract_to} is not empty')
    header = rows = None
    head_raw = rows_raw = None
    actual, local, contents = {}, {}, {}
    total, n = 0, 0
    names = set()
    try:
        tf = tarfile.open(path, mode='r:gz')
    except (tarfile.TarError, OSError, EOFError) as e:
        raise BundleError('bad_archive', f'not a readable tar.gz: {type(e).__name__}: {e}')
    with tf:
        while True:
            try:
                m = tf.next()
            except _ARCHIVE_ERRORS as e:
                raise BundleError('bad_archive', f'corrupt archive: {type(e).__name__}: {e}')
            if m is None:
                break
            name = m.name
            if m.isdir():
                check_relpath(name.rstrip('/'), 'directory member')
                continue
            if not m.isreg():
                raise BundleError('bad_member', f'{name!r}: only regular files are allowed (type {m.type!r})')
            check_relpath(name, 'member')
            if name in names:
                raise BundleError('bad_member', f'duplicate member {name!r}')
            names.add(name)
            n += 1
            if n > MAX_FILES + 2:
                raise BundleError('too_big', f'more than {MAX_FILES} files')
            if m.size > MAX_FILE_BYTES:
                raise BundleError('too_big', f'{name}: {m.size} bytes > {MAX_FILE_BYTES}')
            total += m.size
            if total > MAX_TOTAL_BYTES:
                raise BundleError('too_big', f'uncompressed size > {MAX_TOTAL_BYTES}')
            f = tf.extractfile(m)
            if name in (HEADER_NAME, ROWS_NAME):
                try:
                    data = f.read()
                except _ARCHIVE_ERRORS as e:
                    raise BundleError('bad_archive', f'{name}: corrupt data: {type(e).__name__}: {e}')
                if name == HEADER_NAME:
                    head_raw = data
                else:
                    rows_raw = data
                continue
            if not name.startswith(SCRIPTS + '/'):
                raise BundleError('bad_layout', f'unexpected member {name!r} (allowed: {HEADER_NAME}, {ROWS_NAME}, scripts/...)')
            h = hashlib.sha256()
            got = 0
            out = None
            keep = None
            if m.size <= 64 * 1024 ** 2 and '/'.join(name.split('/')[2:]) in CONTENT_CHECKED and name.count('/') >= 2:
                keep = []
            if extract_to:
                dst = os.path.join(extract_to, *name.split('/'))
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                out = open(dst, 'wb')
            try:
                for b in iter(lambda: f.read(1 << 20), b''):
                    h.update(b)
                    got += len(b)
                    if out:
                        out.write(b)
                    if keep is not None:
                        keep.append(b)
            except _ARCHIVE_ERRORS as e:
                raise BundleError('bad_archive', f'{name}: corrupt data: {type(e).__name__}: {e}')
            finally:
                if out:
                    out.close()
            if got != m.size:
                raise BundleError('bad_archive', f'{name}: truncated ({got} of {m.size} bytes)')
            actual[name] = (got, h.hexdigest())
            if keep is not None:
                contents[name] = b''.join(keep)
            if extract_to:
                local[name] = dst
    if head_raw is None:
        raise BundleError('bad_header', f'{HEADER_NAME} is missing')
    if rows_raw is None:
        raise BundleError('bad_rows', f'{ROWS_NAME} is missing')
    try:
        header = json.loads(head_raw.decode('utf-8'))
    except Exception as e:  # noqa: BLE001
        raise BundleError('bad_header', f'{HEADER_NAME} does not parse: {type(e).__name__}')
    check_header(header)
    for k in ('run', 'model_id'):
        if expect.get(k) and expect[k] != header[k]:
            raise BundleError('bad_header', f'header {k} {header[k]!r} != {expect[k]!r} (from the S3 key)')
    try:
        rows = [json.loads(x) for x in rows_raw.decode('utf-8').splitlines() if x.strip()]
    except Exception as e:  # noqa: BLE001
        raise BundleError('bad_rows', f'{ROWS_NAME} does not parse: {type(e).__name__}')
    if hashlib.sha256(rows_raw).hexdigest() != header['rows_sha256']:
        raise BundleError('sha_mismatch', f'{ROWS_NAME} sha256 differs from bundle.json rows_sha256')
    for p in actual:
        check_relpath(p, 'file')
    warns = check_layout(header, sorted(actual), contents, {p: v[0] for p, v in actual.items()}, lenient=lenient)
    check_rows(header, rows, actual)
    if header['n_files'] != len(actual) or header['bytes'] != sum(v[0] for v in actual.values()):
        raise BundleError('bad_header', 'bundle.json n_files/bytes do not match the files')
    files = {p: local.get(p) for p in sorted(actual)}
    return Verified(header, rows, files, warns, bsha, nb, extract_to)


def redact_url(u):
    """a pre-signed URL without its query string (the query holds the signature + session token): safe to log"""
    try:
        s = urllib.parse.urlsplit(u)
        return f'{s.scheme}://{s.netloc}{s.path}?<signature redacted>'
    except Exception:  # noqa: BLE001
        return '<url redacted>'


class _CorruptTransfer(Exception):
    """the stored object's ETag (= MD5 of a single-part PUT body) differs from the local file's MD5"""


RETRYABLE_400 = ('RequestTimeout', 'IncompleteBody', 'BadDigest')     # S3 400s caused by the transfer, not the URL


def upload_bundle(path, put_url, retries=4, timeout=600):
    """HTTP PUT of a bundle to its pre-signed URL; retries on network errors / 5xx / transfer 400s (RETRYABLE_400) / an
    ETag that is not the body's MD5; other 400s and 403/404/405 (expired or invalid signature, ...) are not retried.
    S3 refuses unsigned Content-MD5 / x-amz-* headers on a pre-signed PUT, so integrity is checked from the response
    instead: for a single-part PUT the ETag is the body's MD5 -> it must equal the local MD5 (else retried, then raises).
    The publisher re-verifies every file's sha256 anyway. Never logs the URL's query string (signature + token)."""
    nb = os.path.getsize(path)
    md5 = _md5_b64(path)
    md5_hex = base64.b64decode(md5).hex()
    sha = sha256_file(path)
    safe_url = redact_url(put_url)
    last = None
    for attempt in range(retries + 1):
        try:
            with open(path, 'rb') as f:
                req = urllib.request.Request(put_url, data=f, method='PUT',
                                             headers={'Content-Length': str(nb), 'Content-Type': 'application/gzip'})
                with urllib.request.urlopen(req, timeout=timeout) as r:
                    etag = (r.headers.get('ETag') or '').strip('"')
                    if re.fullmatch(r'[0-9a-f]{32}', etag) and etag != md5_hex:
                        raise _CorruptTransfer(f'ETag {etag} != local MD5 {md5_hex} (body corrupted in transit)')
                    return dict(status=r.status, etag=etag, etag_is_md5=etag == md5_hex, bytes=nb, sha256=sha, md5_hex=md5_hex,
                                attempts=attempt + 1)
        except urllib.error.HTTPError as e:
            try:
                body = e.read()[:400].decode('utf-8', 'replace')
            except Exception:  # noqa: BLE001
                body = ''
            m = re.search(r'<Code>([^<]+)</Code>', body)
            code = m.group(1) if m else ''
            last = f'HTTP {e.code} {code} for {safe_url}'
            if e.code in (403, 404, 405) or (e.code == 400 and code not in RETRYABLE_400):
                raise RuntimeError(f'bundle upload refused: {last} (expired or invalid pre-signed URL? get fresh URLs)')
        except _CorruptTransfer as e:
            last = f'{e} for {safe_url}'
        except (urllib.error.URLError, OSError, TimeoutError) as e:
            msg = str(e)
            last = (f'{type(e).__name__}: {msg[:200]}' if 'X-Amz-' not in msg and '?' not in msg else type(e).__name__) + f' for {safe_url}'
        if attempt < retries:
            time.sleep(min(60, 2 ** attempt * 3))
    raise RuntimeError(f'bundle upload failed after {retries + 1} attempts: {last}')
