export const meta = {
  name: 'pmp-modal-build-v3',
  description: 'Partial-tier pipeline on Modal (owner-approved): source IFC -> build123d scripts + verification + scripted colour-coded issue model -> published into each partial package scripts/ folder on S3; test end to end on 5 NEW samples incl. publishing',
  phases: [
    { title: 'Build', detail: '6 component builders in parallel' },
    { title: 'Integrate', detail: 'wire the app; run the 5 new samples end to end on Modal incl. publishing into their packages scripts/' },
    { title: 'Review', detail: 'adversarial review of results, published packages and cost' },
  ],
}
const ROOT = '/Users/dhiren/Downloads/Deccan/partial_modal'
const SP = '/private/tmp/claude-501/-Users-dhiren-Downloads-Deccan/5462df30-9e2f-4b34-a06f-5d008d800062/scratchpad'
const OLD = '/private/tmp/claude-501/-Users-dhiren-Downloads-Deccan/f63cb79e-c4e0-4f10-ab61-521e6153b162/scratchpad'
const COMMON = `
## Goal (from the owner, Dhiren, who explicitly approved processing this data on Modal, workspace "navaneeth")
For EVERY partial-tier model (26,733 models in 2,418 packages under s3://bim-proprietary-data/cad-disk-extract/dataset/packages/3d_partial/<pid>/), do what we did by hand for 5 samples, on MODAL, and PUSH the results into the package's own scripts/ folder on S3, next to its model/step, model/ifc, model/db1 (Tekla) files:
 1. SOURCE: faithful source IFC - IFC models: the package IFC (converted_from); DB1: regenerate the IFC from the DB1 with the decoder kit version that produced the shipped STEP, restore GlobalIds from the shipped STEP, prove reproduction; SDS/2: emit an IFC from the SDS/2 job with the pinned converter version.
 2. PIPELINE: our headless deterministic build123d pipeline -> per-model build scripts + schedules + verification (job.py's steps: extract+exact, props, recover, views, verify, reference_defects, verify_levels, tekla_checks, e2e incl. byte-identical determinism).
 3. COLOUR-CODED RECONSTRUCTION, ALSO AS A SHIPPED SCRIPT: scripts/<model>/build_issues_model.py (headless, deterministic, build123d, runs from the package alone like build_model.py) rebuilds the model from the schedules and writes <model>_ISSUES_highlighted.step with every part coloured: GREY ok, RED parts the conversion DROPPED (built ONLY from geometry the SOURCE records - e.g. a DB1 slab outline+thickness, rebar axes - shipped as schedules/missing_parts.json; a clearly labelled marker where the size is unknown), ORANGE approximated by the converter, YELLOW to check, PURPLE not yet perfect in our script; plus <model>_MISSING_parts_only.step when anything is missing. Option --from-delivered colours the package's delivered STEP (model/step/...) instead of our rebuild (that is how the 5 sample overlays were made; the best sample method edits only PRODUCT names + appends colour styling so the delivered geometry stays byte-identical and the file stays small). Labels = clear product names ('MISSING concrete slab 165.1 mm ...', 'APPROX ...'). issues.json (machine-readable: every flagged part id/name/colour/category/reason/source evidence) + WHERE_TO_LOOK.md (plain language for a non-CAD reviewer: per colour what/where in landmarks + mm coordinates/why, counts, legend).
 4. PUBLISH into s3://bim-proprietary-data/cad-disk-extract/dataset/packages/3d_partial/<pid>/scripts/ with this layout:
    scripts/README.md, scripts/requirements.txt (pinned), scripts/steelbuild.py, scripts/issues_lib.py (shared by build_issues_model.py), scripts/scripts_manifest.jsonl (every file we added: path, bytes, sha256, model_id, source, code version),
    scripts/<model_folder>/ build_model.py, build_issues_model.py, model_info.json, schedules/ (parts, profiles, profile_outlines, solids, cuts, cut_boundaries, openings, paths, exact_geometry, assemblies, missing_parts.json, issues.json), verification/ (verification.csv + summaries + e2e results), issues/ (<model>_ISSUES_highlighted.step, <model>_MISSING_parts_only.step, WHERE_TO_LOOK.md), source/ (provenance.json; the regenerated/emitted IFC for DB1/SDS2 models - IFC models already have theirs in model/ifc/).
    <model_folder> = sanitised STEP basename (+ short id suffix on collision); several models per package share scripts/ (shared files identical; merge, never clobber another model's folder). NEVER modify or delete any existing package file outside scripts/ (manifest.jsonl, project.json, model/, drawings/ ... stay untouched).
We TEST ONLY on 5 NEW samples (${ROOT}/new5.json): end to end on Modal INCLUDING publishing into their packages' scripts/ folders. The owner does NOT want the original 5 samples re-run on Modal - never run them (or any other model) on Modal; all Modal unit tests use the new samples n1-n5. The colour-coded STEP files that get published MUST be produced by the shipped scripts/<model>/build_issues_model.py itself (run on Modal from the assembled scripts/ tree, exactly as a user would run it), so the package proves its script generates them. Only after the owner approves do we scale (not part of this task).
## Existing material to REUSE (read; copy into ${ROOT}; never edit originals)
- Previous attempt of this build (stopped after ~15 min; reuse anything useful): ${ROOT}/code/{v9a,db1,sds2}, ${ROOT}/jobs/ (s3cache.py, cache/).
- Pipeline code: v9a ${OLD}/full/code_v9a/; DB1-capable (T profiles etc.) ${OLD}/full/nonifc/code_db1/; SDS/2 copy ${OLD}/full/nonifc/code_sds2/. Runner ${OLD}/full/fleet/benchkit/job.py + run_local.py. Pinned env ${OLD}/full/fleet/requirements.txt; system libs (Debian): libgl1 libxrender1 libxext6 libsm6 libfontconfig1 libxkbcommon0 libxi6. The published perfect-tier sample packages show the scripts/ README/layout conventions: s3://bim-proprietary-data/cad-disk-extract/dataset/samples/parametric_v1/<pid>/scripts/ (read-only) and the staging tool ${OLD}/full/stage/ (stage_full.py, stagelib.py, templates/scripts_README.md).
- DB1 regeneration: ${OLD}/full/nonifc/db1_regen/ (scripts/, kit_manifests/, regen_inputs.json), provenance example ${OLD}/full/nonifc/nonifc_db1_jobs.json; decoder kit /Users/dhiren/Downloads/Deccan/z3conv/db1/ (+ /Users/dhiren/Downloads/Deccan/z3conv/_sprint/db1-code-v/u/); env ifcopenshell 0.8.4.post1 (python 3.11). Bench copies: i-0a8e721cc7429893e /opt/bench/partial_s3_db1_light, i-017d6427d1ba2e850 /opt/bench/partial_s4_db1_heavy (region ap-south-2).
- SDS/2 emission: ${OLD}/full/nonifc/sds2_emitter/ (+ NOTES ${OLD}/full/nonifc/NOTES_sds2_head.md); converters /Users/dhiren/Downloads/Deccan/z3conv/sds2_v5/; bench i-0d3e1ca73ea6876de /opt/bench/partial_s5_sds2, /opt/bench/nonifc_sds2 (ap-south-2).
- Overlays (reference behaviour for step 3): ${SP}/overlay/make_overlay.py (sample 3), ${SP}/overlays/s1,s2,s4,s5/ (final STEPs + WHERE_TO_LOOK.md + overlay_report.json), ${SP}/overlays/s4_work/prep_s4.py; per-sample overlay scripts on bench i-0f35da72bf742063d (Mumbai, default region) /opt/bench/ovl_s1, ovl_s2, ovl_s4, ovl_s5 (bench.sh sh output is cut at ~2.4k chars: copy whole folders with bench.sh pull); the builders' full reports incl. methods: ${SP}/../tasks/w3735x5fh.output (JSON). DB1 skipped-record locator ${SP}/partial/s3_db1_light/probe_out/probe_db1.py. Delivered copies in /Users/dhiren/Downloads/partial_5_samples/.
- Gap analysis per sample: ${SP}/partial/<sample>/ ; synthesis JSON ${SP}/../tasks/wmhcqfhmg.output (result.synthesis, result.samples[].report).
- Earlier bench results for the ORIGINAL samples (reference for how outputs should look; never re-run them): pipeline summaries s1 ${SP}/partial/s1_ifc_c2s/out_v9a/summary.json, s2 ${SP}/partial/s2_ifc_approx/out_v9a/summary.json, s3 ${SP}/partial/s3_db1_light/pipe_db1b/*/summary.json, s4 ${SP}/partial/s4_db1_heavy/pipe/*/summary.json, s5 ${SP}/partial/s5_sds2/pipe/*/summary.json; overlay colour counts in the WHERE_TO_LOOK.md files.
- Partial data: package manifests (row per STEP: relpath, model_id, step_source, converted_from, converted_from_package (add-ons: source in dataset/packages/3d/<pid>/), converter, partial{kind,issues,missing,standins}, grader, verify_codes, step_key/source_key); all rows /Users/dhiren/Downloads/Deccan/report_v1/data/projects_p1.json; conversion detail: DB1 .../{zenitude-data-3/_state/conv|zentitude-data-4/_state/conv2}/db1/{detail,results}/<model_id>.*; IFC .../conversions/ifc-step/<model_id>.<suffix>.step(+.check.json,.parts.json); SDS/2 .../zenitude-data-3/conversions/sds2-step/<jobid>/... + _state/conv/sds2/detail/.
## Fixed architecture
- Modal (client ${ROOT}/.venv/bin/modal, workspace "navaneeth" - SHARED with other teams' apps: never touch other apps; name ours pmp-*). NO AWS credentials on Modal and no Modal secrets with credentials. Inputs: pre-signed GET URLs generated on the Mac with AWS_PROFILE=bim (read-only IAM user; 7-day max). Outputs: (1) Modal Volume "pmp-out" /<model_id>/... (full outputs + logs), and (2) for publishing, ONE tar.gz bundle per model (the exact scripts/<model_folder>/ tree + shared files + scripts_manifest rows) uploaded from Modal with a pre-signed PUT URL to the staging key s3://bim-proprietary-data/cad-disk-extract/_state/pmp/bundles/<run>/<model_id>.tar.gz. PUT URLs are generated on the EC2 box i-0f35da72bf742063d (Mumbai; its instance role may write cad-disk-extract/*; URLs live only as long as its role credentials, ~hours - generate per batch) via SSM: bash /tmp/z3c/ssmcli.sh ap-south-1 i-0f35da72bf742063d <script> (or /tmp/z3c/bench.sh). The PUBLISHER runs on that box: verifies each bundle (sha256s, layout), merges it into s3://.../3d_partial/<pid>/scripts/ (shared files must be identical - refuse on conflict), regenerates scripts/scripts_manifest.jsonl, never touches anything outside scripts/, idempotent, logs to s3://bim-proprietary-data/cad-disk-extract/_state/pmp/publish/.
- Size classes: S<10MB, M<100MB, L<500MB, XL<1GB; >=1GB = out of scope for v1 (recorded 'too_big_v1'). Explicit cpu/memory/timeout/ephemeral disk per class; retries; failures recorded, never silently skipped; deterministic.
- Code layout under ${ROOT}: app/ (modal_app.py), code/, src_db1/, src_sds2/, issues/ (build_issues_model.py, issues_lib.py, makers that produce issues.json + missing_parts.json + WHERE_TO_LOOK.md), publish/ (presign_put.py, publisher.py), jobs/ (make_jobs.py, presign.py, test5.jsonl, new5.jsonl), docs/README.md.
## Rules
- Compute: no pipeline/geometry/decoder compute on this Mac (writing code, small parsing, Modal client commands OK). Modal runs ONLY for the 5 new test models n1-n5 (+ unit tests on them), <= 10 containers at once; never the full tier, never the original 5.
- S3 WRITES allowed ONLY: (a) the staging prefix cad-disk-extract/_state/pmp/ and (b) scripts/ folders of the 5 NEW sample packages (new5.json) via the publisher. Nothing else. The Mac's SSO role cannot write bim-proprietary-data; writes go through the EC2 box's role. Never delete objects outside _state/pmp/.
- Never fabricate geometry (red = source-recorded geometry only), never loosen tolerances, never hide a failure; honest labels; never print or copy credentials; never touch EC2 instance state (no launch/stop/terminate), GitHub, SendFeedback.
- Write only under ${ROOT}/<your component folder>.
`
const COMPONENTS = [
  { key: 'jobs', task: `JOB LIST + PRESIGN GET. ${ROOT}/jobs/: make_jobs.py -> jobs_partial.jsonl.gz (one row per partial model: model_id, pid, relpath, model_folder name (sanitised, unique within the package over ALL its partial models), step_source, partial_kind, bytes, class, step key, source key(s) (IFC/DB1/SDS2; add-ons via converted_from_package), converter pin, conversion-detail keys the issue makers need, partial record); presign.py (job -> dict of pre-signed GET URLs, 7 days); new5.jsonl (from ${ROOT}/new5.json). Report tier stats (source x class counts/bytes, add-ons, models per package distribution, missing keys).` },
  { key: 'src_db1', task: `DB1 -> IFC Modal stage in ${ROOT}/src_db1/: image with the decoder env (python 3.11, ifcopenshell 0.8.4.post1, numpy...) + kit versions u and v (pick per model from the conversion result / shipped STEP; refuse lost kits like q with a recorded reason); inputs = GET URLs (DB1, shipped STEP, catalog/overlay files); outputs model.ifc (GlobalIds restored) + provenance.json (kit, sha256s, reproduction proof). ALSO expose the decoded SKIPPED records with their geometry (axis O/E, outline, thickness, profile string, record id - the probe_db1.py logic) as skipped_records.json, because the issue maker needs them to draw RED missing parts. Unit test: one Modal call on new sample n1 (and n2, the add-on, if time allows); the reproduction proof against the shipped STEP is the check.` },
  { key: 'src_sds2', task: `SDS/2 -> IFC Modal stage in ${ROOT}/src_sds2/: image with the converter env(s) for the pinned versions the partial tier uses (find them from projects_p1.json sds2 rows / manifests' converter.version); inputs = GET URLs (SDS/2 zip, shipped STEP); outputs model.ifc + provenance.json (version, per-instance-label reproduction proof) + the converter side tables the issue maker needs (pieces with builder/kind/stand-in flags, skipped members, bolt/hole facts) as sds2_facts.json. Unit test: one Modal call on new sample n5.` },
  { key: 'issues', task: `COLOUR-CODED RECONSTRUCTION (shipped scripts) in ${ROOT}/issues/: (1) issues_lib.py + build_issues_model.py (to be copied into each package's scripts/): headless, deterministic, build123d; default mode rebuilds the model from the model's schedules via steelbuild.py (same as build_model.py), colours each part per schedules/issues.json, adds RED parts from schedules/missing_parts.json (only source-recorded geometry: prisms from outline+thickness, cylinders from axis+diameter, profile sweeps, labelled markers when size unknown), writes issues/<model>_ISSUES_highlighted.step and issues/<model>_MISSING_parts_only.step; --from-delivered PATH colours the delivered STEP instead (text-level PRODUCT-name edit + appended colour styling like the final sample overlays, geometry byte-identical; counts verified); --list prints counts per colour. (2) make_issues.py (runs in the pipeline on Modal): from the partial record, conversion detail files (parts.json tags/why/'[approx' names, check.json; DB1 decoded parts + skipped_records.json from src_db1; SDS2 sds2_facts.json from src_sds2), the source IFC and our verification.csv -> schedules/issues.json + schedules/missing_parts.json + issues/WHERE_TO_LOOK.md (landmarks: nearest named parts, levels, edges; mm coordinates; counts per colour; legend). Cover every category the 5 sample overlays handled (read them all: ${SP}/overlay, ${SP}/overlays/*, bench /opt/bench/ovl_s*, reports in ${SP}/../tasks/w3735x5fh.output). Unit test on Modal on new samples n1 and n5: counts must be consistent with each model's partial record (missing/standins counts) - explain every difference; the shipped build_issues_model.py must regenerate the issues STEP files byte-identically.` },
  { key: 'app', task: `MODAL APP in ${ROOT}/app/modal_app.py (+ ${ROOT}/code/): images (pipeline image = pinned requirements + system libs + code: v9a for IFC models, the DB1/SDS2-capable copies where needed - verify behaviour), Volume pmp-out, functions: source (dispatch to src_db1/src_sds2 or download package IFC), pipeline (job.py steps adapted: inputs via GET URLs, outputs to the volume, per-step timeouts, verdict/summary identical in content to job.py's pmx_summary), issues (make_issues + run build_issues_model.py in BOTH modes as its own e2e check: the shipped script must reproduce the issues files), package (assemble the scripts/<model_folder>/ tree + shared files exactly per the layout; scripts_manifest rows with sha256), bundle upload via the pre-signed PUT URL in the job, per-model orchestrator with retries and error capture, driver local_entrypoint (--jobs file --limit --concurrency --run name) writing /index/<run>.jsonl on the volume. docs/README.md (run test, scale, collect, publish). Unit test the pipeline stage on Modal on new sample n4 (IFC c2s, 7 MB, package IFC).` },
  { key: 'publish', task: `PUBLISHING in ${ROOT}/publish/: presign_put.py (runs ON the EC2 box i-0f35da72bf742063d via ssmcli/bench.sh, uses its instance role; input = list of (run, model_id); output = JSON of pre-signed PUT URLs for s3://bim-proprietary-data/cad-disk-extract/_state/pmp/bundles/<run>/<model_id>.tar.gz, expiry = as long as the role credentials allow; the URL list is written by the box to s3://bim-proprietary-data/cad-disk-extract/_state/pmp/presign/<run>.json and read back on the Mac with AWS_PROFILE=bim) and publisher.py (runs ON that box: lists new bundles, verifies sha256/layout, merges into s3://bim-proprietary-data/cad-disk-extract/dataset/packages/3d_partial/<pid>/scripts/ - shared files must match byte-for-byte or refuse, never touch anything outside scripts/, idempotent re-runs, regenerates scripts/scripts_manifest.jsonl from the merged tree, writes a publish log to _state/pmp/publish/<run>.jsonl). Include a --dry-run. Test: presign 1 URL and upload a tiny test bundle with curl into _state/pmp/bundles/test/ (allowed staging prefix), run the publisher in --dry-run and for real against a fake package target under _state/pmp/fakepkg/<pid>/ (allowed) - NOT a real package yet.` },
]
const SCHEMA = { type: 'object', properties: { component: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, how_to_use: { type: 'string' }, tested: { type: 'string' }, open_issues: { type: 'string' } }, required: ['component', 'files', 'how_to_use', 'tested', 'open_issues'] }

phase('Build')
const built = (await parallel(COMPONENTS.map(c => () => agent(`${COMMON}\n## Your component: ${c.key}\n${c.task}\nReturn the structured result.`, { label: `build:${c.key}`, phase: 'Build', schema: SCHEMA })))).filter(Boolean)
log(`components built: ${built.map(b => b.component).join(', ')}`)

phase('Integrate')
const integB = await agent(`${COMMON}
## Integration + test on the 5 NEW samples (end to end incl. publishing)
Components: ${JSON.stringify(built)}
Wire everything so ONE command runs a job list end to end on Modal (source -> pipeline -> issues -> scripts/ tree -> build_issues_model.py run from that tree produces the coloured STEP files -> bundle). Run ${ROOT}/jobs/new5.jsonl end to end on Modal with fresh PUT URLs from the EC2 box; then run the publisher (first --dry-run, then for real) to merge the 5 bundles into their real packages' scripts/ folders (ONLY those 5 packages, ONLY scripts/). Verify from S3 (read-only listing + download of the published scripts/ trees to ${ROOT}/testB_results/<pid>/): layout exactly as specified, scripts_manifest.jsonl sha256s match, nothing outside scripts/ changed (compare the package manifest.jsonl/project.json etags before/after), and on Modal run the published build_model.py and build_issues_model.py from the downloaded trees -> they reproduce the model and the colour-coded STEP. Fix and iterate until all 5 publish cleanly. Write ${ROOT}/testB_results/REPORT.md (per model: source route, parts, perfect, colour counts vs the partial record, published S3 paths, per-stage time, cpu-seconds, peak memory, Modal cost with stated price source). Return the report.`, { label: 'integrate:testB', phase: 'Integrate' })

phase('Review')
const reviews = await parallel(['correctness', 'publish_safety', 'scale_cost'].map(lens => () => agent(`${COMMON}
## Adversarial review (${lens})
Test on 5 new samples: ${integB}
Inspect ${ROOT} (code + test results) and the 5 published packages' scripts/ (read-only S3, AWS_PROFILE=bim). ${{
  correctness: 'Try to refute: results are correct (spot-check parts against the source IFC / DB1 records); shipped scripts (build_model.py, build_issues_model.py) reproduce the published files; RED parts only from source-recorded geometry; colours/labels right; failures not swallowed; determinism; GUID restore; presign expiry handling; volume races.',
  publish_safety: 'Try to refute: nothing outside scripts/ was touched in the 5 packages (etags/listing), shared files merge safely across models of one package, re-runs idempotent, a partially failed model cannot leave a half-written scripts/ folder, scripts_manifest correct, no credentials anywhere in published files or images.',
  scale_cost: 'Try to refute the scale plan: per-model cost/time by source x class extrapolated to all 26,733 (minus >=1GB), AWS egress (GET from S3 to Modal) volume+cost, PUT URL refresh cadence, Modal concurrency/quotas in a SHARED workspace, memory for L/XL, publisher throughput, time-to-finish. Give a corrected cost/time table with assumptions.',
}[lens]}
Read-only. Return a verdict + concrete findings (file:line).`, { label: `review:${lens}`, phase: 'Review' })))
return { built, integB, reviews }
